name: Build and Update Docs

on:
  push:
    branches: [ main ]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          conda install pytorch cpuonly -c pytorch-nightly
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          python setup.py sdist bdist_wheel
          pip install dist/*.whl
      - name: Run unit tests
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          pytest tests -vv
  build_docs:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: test
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          conda install pytorch cpuonly -c pytorch-nightly
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          python setup.py sdist bdist_wheel
          pip install dist/*.whl
      - name: Build docs
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          cd docs
          pip install -r requirements.txt
          make html
          touch build/html/.nojekyll
          cd ..
      - name: Deploy docs to Github pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
            ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: docs/build/html # The folder the action should deploy.
